# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'composition_masi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 344)
        Form.setMaximumSize(QtCore.QSize(400, 344))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.lbl_id = QtWidgets.QLabel(Form)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.txt_id = QtWidgets.QLineEdit(Form)
        self.txt_id.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_id.setObjectName("txt_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_id)
        self.lbl_date_marche = QtWidgets.QLabel(Form)
        self.lbl_date_marche.setObjectName("lbl_date_marche")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_date_marche)
        self.dt_date_marche = QtWidgets.QDateEdit(Form)
        self.dt_date_marche.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dt_date_marche.setCalendarPopup(True)
        self.dt_date_marche.setObjectName("dt_date_marche")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dt_date_marche)
        self.lbl_code_titre = QtWidgets.QLabel(Form)
        self.lbl_code_titre.setObjectName("lbl_code_titre")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_code_titre)
        self.txt_code_titre = QtWidgets.QLineEdit(Form)
        self.txt_code_titre.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_code_titre.setObjectName("txt_code_titre")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_code_titre)
        self.lbl_cours = QtWidgets.QLabel(Form)
        self.lbl_cours.setObjectName("lbl_cours")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_cours)
        self.txt_cours = QtWidgets.QLineEdit(Form)
        self.txt_cours.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_cours.setObjectName("txt_cours")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_cours)
        self.lbl_total_titre = QtWidgets.QLabel(Form)
        self.lbl_total_titre.setObjectName("lbl_total_titre")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_total_titre)
        self.txt_total_titre = QtWidgets.QLineEdit(Form)
        self.txt_total_titre.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_total_titre.setObjectName("txt_total_titre")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_total_titre)
        self.lbl_facteur_flottant = QtWidgets.QLabel(Form)
        self.lbl_facteur_flottant.setObjectName("lbl_facteur_flottant")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_facteur_flottant)
        self.txt_facteur_flottant = QtWidgets.QLineEdit(Form)
        self.txt_facteur_flottant.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_facteur_flottant.setObjectName("txt_facteur_flottant")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_facteur_flottant)
        self.lbl_facteur_plafonnement = QtWidgets.QLabel(Form)
        self.lbl_facteur_plafonnement.setObjectName("lbl_facteur_plafonnement")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_facteur_plafonnement)
        self.txt_facteur_plafonnement = QtWidgets.QLineEdit(Form)
        self.txt_facteur_plafonnement.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_facteur_plafonnement.setObjectName("txt_facteur_plafonnement")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_facteur_plafonnement)
        self.lbl_capi_flottante = QtWidgets.QLabel(Form)
        self.lbl_capi_flottante.setObjectName("lbl_capi_flottante")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_capi_flottante)
        self.txt_capi_flottante = QtWidgets.QLineEdit(Form)
        self.txt_capi_flottante.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_capi_flottante.setObjectName("txt_capi_flottante")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_capi_flottante)
        self.lbl_poids = QtWidgets.QLabel(Form)
        self.lbl_poids.setObjectName("lbl_poids")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_poids)
        self.txt_poids = QtWidgets.QLineEdit(Form)
        self.txt_poids.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_poids.setObjectName("txt_poids")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txt_poids)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bu_add = QtWidgets.QPushButton(Form)
        self.bu_add.setObjectName("bu_add")
        self.verticalLayout.addWidget(self.bu_add)
        self.bu_delete = QtWidgets.QPushButton(Form)
        self.bu_delete.setObjectName("bu_delete")
        self.verticalLayout.addWidget(self.bu_delete)
        self.bu_close = QtWidgets.QPushButton(Form)
        self.bu_close.setObjectName("bu_close")
        self.verticalLayout.addWidget(self.bu_close)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.txt_description = QtWidgets.QTextEdit(Form)
        self.txt_description.setMaximumSize(QtCore.QSize(16777215, 50))
        self.txt_description.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_description.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_description.setTabChangesFocus(True)
        self.txt_description.setDocumentTitle("")
        self.txt_description.setUndoRedoEnabled(False)
        self.txt_description.setReadOnly(True)
        self.txt_description.setAcceptRichText(True)
        self.txt_description.setObjectName("txt_description")
        self.verticalLayout_2.addWidget(self.txt_description)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "COMPOSITION MASI"))
        self.lbl_id.setText(_translate("Form", "id "))
        self.lbl_date_marche.setText(_translate("Form", "Date marche"))
        self.lbl_code_titre.setText(_translate("Form", "Code titre"))
        self.lbl_cours.setText(_translate("Form", "Cours"))
        self.lbl_total_titre.setText(_translate("Form", "Total titres"))
        self.lbl_facteur_flottant.setText(_translate("Form", "Facteur flottant"))
        self.lbl_facteur_plafonnement.setText(_translate("Form", "Facteur plafonnement"))
        self.lbl_capi_flottante.setText(_translate("Form", "Capi flottante"))
        self.lbl_poids.setText(_translate("Form", "Poids"))
        self.bu_add.setText(_translate("Form", "Enregistrer"))
        self.bu_delete.setText(_translate("Form", "Supprimer"))
        self.bu_close.setText(_translate("Form", "Fermer"))
        self.txt_description.setToolTip(_translate("Form", "Block d\'affichage des messages système."))
        self.txt_description.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.txt_description.setPlaceholderText(_translate("Form", "Messages Système"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

