# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fonds_market.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 315)
        Form.setMaximumSize(QtCore.QSize(550, 315))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.lbl_id = QtWidgets.QLabel(Form)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.txt_id = QtWidgets.QLineEdit(Form)
        self.txt_id.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_id.setObjectName("txt_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_id)
        self.lbl_code_isin = QtWidgets.QLabel(Form)
        self.lbl_code_isin.setObjectName("lbl_code_isin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_code_isin)
        self.txt_code_isin = QtWidgets.QLineEdit(Form)
        self.txt_code_isin.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_code_isin.setObjectName("txt_code_isin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_code_isin)
        self.lbl_code_fonds = QtWidgets.QLabel(Form)
        self.lbl_code_fonds.setObjectName("lbl_code_fonds")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_code_fonds)
        self.txt_code_fonds = QtWidgets.QLineEdit(Form)
        self.txt_code_fonds.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_code_fonds.setObjectName("txt_code_fonds")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_code_fonds)
        self.lbl_description = QtWidgets.QLabel(Form)
        self.lbl_description.setObjectName("lbl_description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_description)
        self.txt_description = QtWidgets.QLineEdit(Form)
        self.txt_description.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_description.setObjectName("txt_description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_description)
        self.lbl_forme_juridique = QtWidgets.QLabel(Form)
        self.lbl_forme_juridique.setObjectName("lbl_forme_juridique")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_forme_juridique)
        self.txt_forme_juridique = QtWidgets.QLineEdit(Form)
        self.txt_forme_juridique.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_forme_juridique.setObjectName("txt_forme_juridique")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_forme_juridique)
        self.lbl_categorie = QtWidgets.QLabel(Form)
        self.lbl_categorie.setObjectName("lbl_categorie")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_categorie)
        self.txt_categorie = QtWidgets.QLineEdit(Form)
        self.txt_categorie.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_categorie.setObjectName("txt_categorie")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_categorie)
        self.lbl_sdg = QtWidgets.QLabel(Form)
        self.lbl_sdg.setObjectName("lbl_sdg")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_sdg)
        self.txt_sdg = QtWidgets.QLineEdit(Form)
        self.txt_sdg.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_sdg.setObjectName("txt_sdg")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_sdg)
        self.lbl_depositaire = QtWidgets.QLabel(Form)
        self.lbl_depositaire.setObjectName("lbl_depositaire")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_depositaire)
        self.txt_depositaire = QtWidgets.QLineEdit(Form)
        self.txt_depositaire.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_depositaire.setObjectName("txt_depositaire")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_depositaire)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setHorizontalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_reseau_placeur = QtWidgets.QLabel(Form)
        self.lbl_reseau_placeur.setObjectName("lbl_reseau_placeur")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_reseau_placeur)
        self.txt_reseau_placeur = QtWidgets.QLineEdit(Form)
        self.txt_reseau_placeur.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_reseau_placeur.setObjectName("txt_reseau_placeur")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_reseau_placeur)
        self.lbl_periodicite = QtWidgets.QLabel(Form)
        self.lbl_periodicite.setObjectName("lbl_periodicite")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_periodicite)
        self.txt_periodicite = QtWidgets.QLineEdit(Form)
        self.txt_periodicite.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_periodicite.setObjectName("txt_periodicite")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_periodicite)
        self.lbl_benchmark = QtWidgets.QLabel(Form)
        self.lbl_benchmark.setObjectName("lbl_benchmark")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_benchmark)
        self.txt_benchmark = QtWidgets.QLineEdit(Form)
        self.txt_benchmark.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_benchmark.setObjectName("txt_benchmark")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_benchmark)
        self.lbl_type_gestion = QtWidgets.QLabel(Form)
        self.lbl_type_gestion.setObjectName("lbl_type_gestion")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_type_gestion)
        self.txt_type_gestion = QtWidgets.QLineEdit(Form)
        self.txt_type_gestion.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_type_gestion.setObjectName("txt_type_gestion")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_type_gestion)
        self.lbl_affectation_resultat = QtWidgets.QLabel(Form)
        self.lbl_affectation_resultat.setObjectName("lbl_affectation_resultat")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_affectation_resultat)
        self.txt_affectation_resultat = QtWidgets.QLineEdit(Form)
        self.txt_affectation_resultat.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_affectation_resultat.setObjectName("txt_affectation_resultat")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_affectation_resultat)
        self.lbl_frais_gestion = QtWidgets.QLabel(Form)
        self.lbl_frais_gestion.setObjectName("lbl_frais_gestion")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_frais_gestion)
        self.txt_frais_gestion = QtWidgets.QLineEdit(Form)
        self.txt_frais_gestion.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_frais_gestion.setObjectName("txt_frais_gestion")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_frais_gestion)
        self.lbl_frait_rachat = QtWidgets.QLabel(Form)
        self.lbl_frait_rachat.setObjectName("lbl_frait_rachat")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_frait_rachat)
        self.txt_frais_rachat = QtWidgets.QLineEdit(Form)
        self.txt_frais_rachat.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_frais_rachat.setObjectName("txt_frais_rachat")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_frais_rachat)
        self.lbl_frais_souscription = QtWidgets.QLabel(Form)
        self.lbl_frais_souscription.setObjectName("lbl_frais_souscription")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_frais_souscription)
        self.txt_frais_souscription = QtWidgets.QLineEdit(Form)
        self.txt_frais_souscription.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_frais_souscription.setObjectName("txt_frais_souscription")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_frais_souscription)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bu_add = QtWidgets.QPushButton(Form)
        self.bu_add.setObjectName("bu_add")
        self.verticalLayout.addWidget(self.bu_add)
        self.bu_delete = QtWidgets.QPushButton(Form)
        self.bu_delete.setObjectName("bu_delete")
        self.verticalLayout.addWidget(self.bu_delete)
        self.bu_close = QtWidgets.QPushButton(Form)
        self.bu_close.setObjectName("bu_close")
        self.verticalLayout.addWidget(self.bu_close)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.txt_description_2 = QtWidgets.QTextEdit(Form)
        self.txt_description_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.txt_description_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_description_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_description_2.setTabChangesFocus(True)
        self.txt_description_2.setDocumentTitle("")
        self.txt_description_2.setUndoRedoEnabled(False)
        self.txt_description_2.setReadOnly(True)
        self.txt_description_2.setAcceptRichText(True)
        self.txt_description_2.setObjectName("txt_description_2")
        self.verticalLayout_2.addWidget(self.txt_description_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FONDS MARKET"))
        self.lbl_id.setText(_translate("Form", "id"))
        self.lbl_code_isin.setText(_translate("Form", "Code isin"))
        self.lbl_code_fonds.setText(_translate("Form", "Code fonds"))
        self.lbl_description.setText(_translate("Form", "Description"))
        self.lbl_forme_juridique.setText(_translate("Form", "Forme juridique"))
        self.lbl_categorie.setText(_translate("Form", "Categorie"))
        self.lbl_sdg.setText(_translate("Form", "SDG"))
        self.lbl_depositaire.setText(_translate("Form", "Depositaire"))
        self.lbl_reseau_placeur.setText(_translate("Form", "Reseau placeur"))
        self.lbl_periodicite.setText(_translate("Form", "Periodicite"))
        self.lbl_benchmark.setText(_translate("Form", "Indice benchmark"))
        self.lbl_type_gestion.setText(_translate("Form", "Type gestion"))
        self.lbl_affectation_resultat.setText(_translate("Form", "Affectation resultat"))
        self.lbl_frais_gestion.setText(_translate("Form", "Frais gestion"))
        self.lbl_frait_rachat.setText(_translate("Form", "Frais rachat"))
        self.lbl_frais_souscription.setText(_translate("Form", "Frais souscription"))
        self.bu_add.setText(_translate("Form", "Enregistrer"))
        self.bu_delete.setText(_translate("Form", "Supprimer"))
        self.bu_close.setText(_translate("Form", "Fermer"))
        self.txt_description_2.setToolTip(_translate("Form", "Block d\'affichage des messages système."))
        self.txt_description_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.txt_description_2.setPlaceholderText(_translate("Form", "Messages Système"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

