# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pays.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 373)
        Form.setMaximumSize(QtCore.QSize(400, 410))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.lbl_id = QtWidgets.QLabel(Form)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.txt_id = QtWidgets.QLineEdit(Form)
        self.txt_id.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_id.setObjectName("txt_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_id)
        self.lbl_code = QtWidgets.QLabel(Form)
        self.lbl_code.setObjectName("lbl_code")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_code)
        self.txt_code = QtWidgets.QLineEdit(Form)
        self.txt_code.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_code.setObjectName("txt_code")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_code)
        self.lbl_description = QtWidgets.QLabel(Form)
        self.lbl_description.setObjectName("lbl_description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_description)
        self.txt_description = QtWidgets.QLineEdit(Form)
        self.txt_description.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_description.setObjectName("txt_description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_description)
        self.lbl_alpha2 = QtWidgets.QLabel(Form)
        self.lbl_alpha2.setObjectName("lbl_alpha2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_alpha2)
        self.txt_alpha2 = QtWidgets.QLineEdit(Form)
        self.txt_alpha2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_alpha2.setObjectName("txt_alpha2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_alpha2)
        self.lbl_alpha3 = QtWidgets.QLabel(Form)
        self.lbl_alpha3.setObjectName("lbl_alpha3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_alpha3)
        self.txt_alpha3 = QtWidgets.QLineEdit(Form)
        self.txt_alpha3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_alpha3.setObjectName("txt_alpha3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_alpha3)
        self.lbl_region = QtWidgets.QLabel(Form)
        self.lbl_region.setObjectName("lbl_region")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_region)
        self.txt_region = QtWidgets.QLineEdit(Form)
        self.txt_region.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_region.setObjectName("txt_region")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_region)
        self.lbl_region_code = QtWidgets.QLabel(Form)
        self.lbl_region_code.setObjectName("lbl_region_code")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_region_code)
        self.txt_region_code = QtWidgets.QLineEdit(Form)
        self.txt_region_code.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_region_code.setObjectName("txt_region_code")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_region_code)
        self.lbl_sub_region = QtWidgets.QLabel(Form)
        self.lbl_sub_region.setObjectName("lbl_sub_region")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_sub_region)
        self.txt_sub_region = QtWidgets.QLineEdit(Form)
        self.txt_sub_region.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_sub_region.setObjectName("txt_sub_region")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_sub_region)
        self.lbl_sub_region_code = QtWidgets.QLabel(Form)
        self.lbl_sub_region_code.setObjectName("lbl_sub_region_code")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_sub_region_code)
        self.txt_sub_region_code = QtWidgets.QLineEdit(Form)
        self.txt_sub_region_code.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_sub_region_code.setObjectName("txt_sub_region_code")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txt_sub_region_code)
        self.lbl_iso_version = QtWidgets.QLabel(Form)
        self.lbl_iso_version.setObjectName("lbl_iso_version")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_iso_version)
        self.txt_iso_version = QtWidgets.QLineEdit(Form)
        self.txt_iso_version.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_iso_version.setObjectName("txt_iso_version")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.txt_iso_version)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bu_add = QtWidgets.QPushButton(Form)
        self.bu_add.setObjectName("bu_add")
        self.verticalLayout.addWidget(self.bu_add)
        self.bu_delete = QtWidgets.QPushButton(Form)
        self.bu_delete.setObjectName("bu_delete")
        self.verticalLayout.addWidget(self.bu_delete)
        self.bu_close = QtWidgets.QPushButton(Form)
        self.bu_close.setObjectName("bu_close")
        self.verticalLayout.addWidget(self.bu_close)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.txt_description_2 = QtWidgets.QTextEdit(Form)
        self.txt_description_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.txt_description_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_description_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_description_2.setTabChangesFocus(True)
        self.txt_description_2.setDocumentTitle("")
        self.txt_description_2.setUndoRedoEnabled(False)
        self.txt_description_2.setReadOnly(True)
        self.txt_description_2.setAcceptRichText(True)
        self.txt_description_2.setObjectName("txt_description_2")
        self.verticalLayout_2.addWidget(self.txt_description_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PAYS"))
        self.lbl_id.setText(_translate("Form", "id"))
        self.lbl_code.setText(_translate("Form", "Code"))
        self.lbl_description.setText(_translate("Form", "Description"))
        self.lbl_alpha2.setText(_translate("Form", "Alpha2"))
        self.lbl_alpha3.setText(_translate("Form", "Alpha3"))
        self.lbl_region.setText(_translate("Form", "Region"))
        self.lbl_region_code.setText(_translate("Form", "Region code"))
        self.lbl_sub_region.setText(_translate("Form", "Sub region"))
        self.lbl_sub_region_code.setText(_translate("Form", "Sub region code"))
        self.lbl_iso_version.setText(_translate("Form", "Iso version"))
        self.bu_add.setText(_translate("Form", "Enregistrer"))
        self.bu_delete.setText(_translate("Form", "Supprimer"))
        self.bu_close.setText(_translate("Form", "Fermer"))
        self.txt_description_2.setToolTip(_translate("Form", "Block d\'affichage des messages système."))
        self.txt_description_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.txt_description_2.setPlaceholderText(_translate("Form", "Messages Système"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

