# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'titre_market.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 460)
        Form.setMaximumSize(QtCore.QSize(650, 460))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.lbl_id = QtWidgets.QLabel(Form)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.txt_id = QtWidgets.QLineEdit(Form)
        self.txt_id.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_id.setObjectName("txt_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_id)
        self.lbl_code = QtWidgets.QLabel(Form)
        self.lbl_code.setObjectName("lbl_code")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_code)
        self.txt_code = QtWidgets.QLineEdit(Form)
        self.txt_code.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_code.setObjectName("txt_code")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_code)
        self.lbl_isin = QtWidgets.QLabel(Form)
        self.lbl_isin.setObjectName("lbl_isin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_isin)
        self.txt_isin = QtWidgets.QLineEdit(Form)
        self.txt_isin.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_isin.setObjectName("txt_isin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_isin)
        self.lbl_classe = QtWidgets.QLabel(Form)
        self.lbl_classe.setObjectName("lbl_classe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_classe)
        self.txt_classe = QtWidgets.QLineEdit(Form)
        self.txt_classe.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_classe.setObjectName("txt_classe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_classe)
        self.lbl_categorie = QtWidgets.QLabel(Form)
        self.lbl_categorie.setObjectName("lbl_categorie")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_categorie)
        self.txt_categorie = QtWidgets.QLineEdit(Form)
        self.txt_categorie.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_categorie.setObjectName("txt_categorie")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_categorie)
        self.lbl_description = QtWidgets.QLabel(Form)
        self.lbl_description.setObjectName("lbl_description")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_description)
        self.txt_description = QtWidgets.QLineEdit(Form)
        self.txt_description.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_description.setObjectName("txt_description")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_description)
        self.lbl_nominal = QtWidgets.QLabel(Form)
        self.lbl_nominal.setObjectName("lbl_nominal")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_nominal)
        self.txt_nominal = QtWidgets.QLineEdit(Form)
        self.txt_nominal.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_nominal.setObjectName("txt_nominal")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_nominal)
        self.lbl_type_coupon = QtWidgets.QLabel(Form)
        self.lbl_type_coupon.setObjectName("lbl_type_coupon")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_type_coupon)
        self.txt_type_coupon = QtWidgets.QLineEdit(Form)
        self.txt_type_coupon.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_type_coupon.setObjectName("txt_type_coupon")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_type_coupon)
        self.lbl_isin_emetteur = QtWidgets.QLabel(Form)
        self.lbl_isin_emetteur.setObjectName("lbl_isin_emetteur")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_isin_emetteur)
        self.txt_isin_emetteur = QtWidgets.QLineEdit(Form)
        self.txt_isin_emetteur.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_isin_emetteur.setObjectName("txt_isin_emetteur")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txt_isin_emetteur)
        self.lbl_code_emetteur = QtWidgets.QLabel(Form)
        self.lbl_code_emetteur.setObjectName("lbl_code_emetteur")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_code_emetteur)
        self.cb_code_emetteur = QtWidgets.QComboBox(Form)
        self.cb_code_emetteur.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cb_code_emetteur.setObjectName("cb_code_emetteur")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cb_code_emetteur)
        self.lbl_isin_centralisateur = QtWidgets.QLabel(Form)
        self.lbl_isin_centralisateur.setObjectName("lbl_isin_centralisateur")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lbl_isin_centralisateur)
        self.txt_isin_centralisateur = QtWidgets.QLineEdit(Form)
        self.txt_isin_centralisateur.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_isin_centralisateur.setObjectName("txt_isin_centralisateur")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.txt_isin_centralisateur)
        self.lbl_description_emetteur = QtWidgets.QLabel(Form)
        self.lbl_description_emetteur.setObjectName("lbl_description_emetteur")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lbl_description_emetteur)
        self.txt_description_emetteur = QtWidgets.QLineEdit(Form)
        self.txt_description_emetteur.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_description_emetteur.setObjectName("txt_description_emetteur")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.txt_description_emetteur)
        self.lbl_description_entralisateur = QtWidgets.QLabel(Form)
        self.lbl_description_entralisateur.setObjectName("lbl_description_entralisateur")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lbl_description_entralisateur)
        self.txt_description_centralisateur = QtWidgets.QLineEdit(Form)
        self.txt_description_centralisateur.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_description_centralisateur.setObjectName("txt_description_centralisateur")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.txt_description_centralisateur)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setHorizontalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_taux_facial = QtWidgets.QLabel(Form)
        self.lbl_taux_facial.setObjectName("lbl_taux_facial")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_taux_facial)
        self.txt_taux_facial = QtWidgets.QLineEdit(Form)
        self.txt_taux_facial.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_taux_facial.setObjectName("txt_taux_facial")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_taux_facial)
        self.lbl_emission = QtWidgets.QLabel(Form)
        self.lbl_emission.setObjectName("lbl_emission")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_emission)
        self.dt_emission = QtWidgets.QDateEdit(Form)
        self.dt_emission.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dt_emission.setCalendarPopup(True)
        self.dt_emission.setObjectName("dt_emission")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dt_emission)
        self.lbl_jouissance = QtWidgets.QLabel(Form)
        self.lbl_jouissance.setObjectName("lbl_jouissance")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_jouissance)
        self.dt_jouissance = QtWidgets.QDateEdit(Form)
        self.dt_jouissance.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dt_jouissance.setCalendarPopup(True)
        self.dt_jouissance.setObjectName("dt_jouissance")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dt_jouissance)
        self.lbl_echeance = QtWidgets.QLabel(Form)
        self.lbl_echeance.setObjectName("lbl_echeance")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_echeance)
        self.dt_echeance = QtWidgets.QDateEdit(Form)
        self.dt_echeance.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dt_echeance.setCalendarPopup(True)
        self.dt_echeance.setObjectName("dt_echeance")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dt_echeance)
        self.lbl_qt_emise = QtWidgets.QLabel(Form)
        self.lbl_qt_emise.setObjectName("lbl_qt_emise")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_qt_emise)
        self.txt_qt_emise = QtWidgets.QLineEdit(Form)
        self.txt_qt_emise.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_qt_emise.setObjectName("txt_qt_emise")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_qt_emise)
        self.lbl_periodicite_coupon = QtWidgets.QLabel(Form)
        self.lbl_periodicite_coupon.setObjectName("lbl_periodicite_coupon")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_periodicite_coupon)
        self.txt_periodicite_coupon = QtWidgets.QLineEdit(Form)
        self.txt_periodicite_coupon.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_periodicite_coupon.setObjectName("txt_periodicite_coupon")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_periodicite_coupon)
        self.lbl_forme_detention = QtWidgets.QLabel(Form)
        self.lbl_forme_detention.setObjectName("lbl_forme_detention")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_forme_detention)
        self.txt_forme_detention = QtWidgets.QLineEdit(Form)
        self.txt_forme_detention.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_forme_detention.setObjectName("txt_forme_detention")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_forme_detention)
        self.lbl_spread = QtWidgets.QLabel(Form)
        self.lbl_spread.setObjectName("lbl_spread")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_spread)
        self.txt_spread = QtWidgets.QLineEdit(Form)
        self.txt_spread.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_spread.setObjectName("txt_spread")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_spread)
        self.lbl_code_alpha2 = QtWidgets.QLabel(Form)
        self.lbl_code_alpha2.setObjectName("lbl_code_alpha2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_code_alpha2)
        self.cb_code_alpha2 = QtWidgets.QComboBox(Form)
        self.cb_code_alpha2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cb_code_alpha2.setObjectName("cb_code_alpha2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cb_code_alpha2)
        self.lbl_code_devise = QtWidgets.QLabel(Form)
        self.lbl_code_devise.setObjectName("lbl_code_devise")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_code_devise)
        self.cb_code_devise = QtWidgets.QComboBox(Form)
        self.cb_code_devise.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cb_code_devise.setObjectName("cb_code_devise")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cb_code_devise)
        self.lbl_ticker = QtWidgets.QLabel(Form)
        self.lbl_ticker.setObjectName("lbl_ticker")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lbl_ticker)
        self.txt_ticker = QtWidgets.QLineEdit(Form)
        self.txt_ticker.setMaximumSize(QtCore.QSize(120, 16777215))
        self.txt_ticker.setObjectName("txt_ticker")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.txt_ticker)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bu_add = QtWidgets.QPushButton(Form)
        self.bu_add.setObjectName("bu_add")
        self.verticalLayout.addWidget(self.bu_add)
        self.bu_delete = QtWidgets.QPushButton(Form)
        self.bu_delete.setObjectName("bu_delete")
        self.verticalLayout.addWidget(self.bu_delete)
        self.bu_close = QtWidgets.QPushButton(Form)
        self.bu_close.setObjectName("bu_close")
        self.verticalLayout.addWidget(self.bu_close)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.txt_description_2 = QtWidgets.QTextEdit(Form)
        self.txt_description_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.txt_description_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_description_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_description_2.setTabChangesFocus(True)
        self.txt_description_2.setDocumentTitle("")
        self.txt_description_2.setUndoRedoEnabled(False)
        self.txt_description_2.setReadOnly(True)
        self.txt_description_2.setAcceptRichText(True)
        self.txt_description_2.setObjectName("txt_description_2")
        self.verticalLayout_2.addWidget(self.txt_description_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TITRE MARKET"))
        self.lbl_id.setText(_translate("Form", "id"))
        self.lbl_code.setText(_translate("Form", "Code"))
        self.lbl_isin.setText(_translate("Form", "Isin"))
        self.lbl_classe.setText(_translate("Form", "Classe"))
        self.lbl_categorie.setText(_translate("Form", "Categorie"))
        self.lbl_description.setText(_translate("Form", "Description"))
        self.lbl_nominal.setText(_translate("Form", "Nominal"))
        self.lbl_type_coupon.setText(_translate("Form", "Type coupon"))
        self.lbl_isin_emetteur.setText(_translate("Form", "Isin emetteur"))
        self.lbl_code_emetteur.setText(_translate("Form", "Code emetteur"))
        self.lbl_isin_centralisateur.setText(_translate("Form", "Isin centralisateur"))
        self.lbl_description_emetteur.setText(_translate("Form", "Description_emetteur"))
        self.lbl_description_entralisateur.setText(_translate("Form", "Description centralisateur"))
        self.lbl_taux_facial.setText(_translate("Form", "Taux facial"))
        self.lbl_emission.setText(_translate("Form", "Emission"))
        self.lbl_jouissance.setText(_translate("Form", "Jouissance"))
        self.lbl_echeance.setText(_translate("Form", "Echeance"))
        self.lbl_qt_emise.setText(_translate("Form", "Quantite emise"))
        self.lbl_periodicite_coupon.setText(_translate("Form", "Periodicite coupon"))
        self.lbl_forme_detention.setText(_translate("Form", "Forme detention"))
        self.lbl_spread.setText(_translate("Form", "Spread"))
        self.lbl_code_alpha2.setText(_translate("Form", "Code alpha2"))
        self.lbl_code_devise.setText(_translate("Form", "Code devise"))
        self.lbl_ticker.setText(_translate("Form", "Ticker"))
        self.bu_add.setText(_translate("Form", "Enregistrer"))
        self.bu_delete.setText(_translate("Form", "Supprimer"))
        self.bu_close.setText(_translate("Form", "Fermer"))
        self.txt_description_2.setToolTip(_translate("Form", "Block d\'affichage des messages système."))
        self.txt_description_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.txt_description_2.setPlaceholderText(_translate("Form", "Messages Système"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

